# **1.Friday-WorkingHours-Afternoon-DDos.pcap_ISCX**

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CICIDS2017/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

print("\nLabel distribution:")
print(df[" Label"].value_counts())

Label distribution:
 Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

# Clean obvious bad values (ONLY for inspection)

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

print("After cleaning:")
print(df[" Label"].value_counts())

After cleaning:
 Label
DDoS      128025
BENIGN     97686
Name: count, dtype: int64

# Create consistent labeling structure

In [ ]:
df[" label"] = df[" Label"].str.strip()

df[" attack_family"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "DDoS"
)

# Keep fine-grained attack info if available
df[" attack_type"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "DDoS"
)

df.drop(columns=[" Label"], inplace=True)

# Balance the dataset (1:1)

In [ ]:
attack_df = df[df[" attack_type"] == "DDoS"]
benign_df = df[df[" attack_type"] == "Benign"]

attack_sample = attack_df.sample(
    n=len(benign_df),
    random_state=42
)

balanced_df = pd.concat([attack_sample, benign_df])
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(balanced_df[" attack_type"].value_counts())

 attack_type
Benign    97686
DDoS      97686
Name: count, dtype: int64

# Save a CLEAN SAMPLE

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/DDoS_clean.csv",
    index=False
)

# **2.Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CICIDS2017/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")

df[' Label'].value_counts()

 Label
PortScan    158930
BENIGN      127537
Name: count, dtype: int64

# Clean infinities & NaNs

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

# Create CONSISTENT LABELS

In [ ]:
df[" label"] = df[" Label"].str.strip()

df[" attack_family"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "Reconnaissance"
)

df[" attack_type"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "PortScan"
)

df.drop(columns=[" Label"], inplace=True)

# Balance classes (1:1)

In [ ]:
attack_df = df[df[" attack_type"] == "PortScan"]
benign_df = df[df[" attack_type"] == "Benign"]

attack_sample = attack_df.sample(
    n=len(benign_df),
    random_state=42
)

balanced_df = pd.concat([attack_sample, benign_df])
balanced_df = balanced_df.sample(frac=1, random_state=42)

# Save clean dataset

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/PortScan_clean.csv",
    index=False
)

# **3.Friday-WorkingHours-Morning.pcap_ISCX**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CICIDS2017/Friday-WorkingHours-Morning.pcap_ISCX.csv")

df[' Label'].value_counts()

 Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64

# Clean infinities & missing values

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

print("After cleaning:")
print(df[" Label"].value_counts())

After cleaning:
 Label
BENIGN    188955
Bot         1956
Name: count, dtype: int64

# Create consistent labels

In [ ]:
df[" label"] = df[" Label"].str.strip()

df[" attack_family"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "Botnet"
)

df[" attack_type"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "Bot"
)

df.drop(columns=[" Label"], inplace=True)

# Balance attack vs benign (1:1)

In [ ]:
attack_df = df[df[" attack_type"] == "Bot"]
benign_df = df[df[" attack_type"] == "Benign"]

benign_sample = benign_df.sample(
    n=len(attack_df),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(balanced_df[" attack_type"].value_counts())

 attack_type
Benign    1956
Bot       1956
Name: count, dtype: int64

# Save cleaned dataset

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/Bot_clean.csv",
    index=False
)

# **4.Monday-WorkingHours.pcap_ISCX**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CICIDS2017/Monday-WorkingHours.pcap_ISCX.csv")

df[' Label'].value_counts()

 Label
BENIGN    529918
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df[" label"] = df[" Label"].str.strip()

df[" attack_family"] = "Benign"
df[" attack_type"] = "Benign"

df.drop(columns=[" Label"], inplace=True)

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/Benign_only.csv",
    index=False
)

# **5.Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CICIDS2017/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")

df[' Label'].value_counts()

 Label
BENIGN          288566
Infiltration        36
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

print("After cleaning:")
print(df[" Label"].value_counts())

After cleaning:
 Label
BENIGN          288359
Infiltration        36
Name: count, dtype: int64

In [ ]:
df[" label"] = df[" Label"].str.strip()

df[" attack_family"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "Infiltration"
)

df[" attack_type"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "Infiltration"
)

df.drop(columns=[" Label"], inplace=True)

In [ ]:
attack_df = df[df[" attack_type"] == "Infiltration"]
benign_df = df[df[" attack_type"] == "Benign"]

benign_sample = benign_df.sample(
    n=len(attack_df),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(balanced_df[" attack_type"].value_counts())

 attack_type
Infiltration    36
Benign          36
Name: count, dtype: int64

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/Infiltration_clean.csv",
    index=False
)

# **6.Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CICIDS2017/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv")

df[' Label'].value_counts()

 Label
BENIGN                        168186
Web Attack � Brute Force        1507
Web Attack � XSS                 652
Web Attack � Sql Injection        21
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df[" label"] = df[" Label"].str.strip()

df[" label"] = df[" label"].replace({
    "Web Attack � Brute Force": "Web Attack - Brute Force",
    "Web Attack � XSS": "Web Attack - XSS",
    "Web Attack � Sql Injection": "Web Attack - SQL Injection"
})

In [ ]:
df[" attack_family"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "WebAttack"
)

df[" attack_type"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else x.replace("Web Attack - ", "")
)

df.drop(columns=[" Label"], inplace=True)

In [ ]:
balanced_parts = []

for attack in ["Brute Force", "XSS", "SQL Injection"]:
    attack_df = df[df[" attack_type"] == attack]
    benign_df = df[df[" attack_type"] == "Benign"]

    benign_sample = benign_df.sample(
        n=len(attack_df),
        random_state=42
    )

    balanced_parts.append(pd.concat([attack_df, benign_sample]))

balanced_df = pd.concat(balanced_parts)
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(balanced_df[" attack_type"].value_counts())

 attack_type
Benign           2180
Brute Force      1507
XSS               652
SQL Injection      21
Name: count, dtype: int64

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/WebAttack_clean.csv",
    index=False
)

# **7.Tuesday-WorkingHours.pcap_ISCX**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CICIDS2017/Tuesday-WorkingHours.pcap_ISCX.csv")

df[' Label'].value_counts()

 Label
BENIGN         432074
FTP-Patator      7938
SSH-Patator      5897
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df[" label"] = df[" Label"].str.strip()
df[" attack_family"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else "BruteForce"
)

df[" attack_type"] = df[" label"].apply(
    lambda x: "Benign" if x == "BENIGN" else x
)

df.drop(columns=[" Label"], inplace=True)

In [ ]:
balanced_parts = []

for attack in ["FTP-Patator", "SSH-Patator"]:
    attack_df = df[df[" attack_type"] == attack]
    benign_df = df[df[" attack_type"] == "Benign"]

    benign_sample = benign_df.sample(
        n=len(attack_df),
        random_state=42
    )

    balanced_parts.append(pd.concat([attack_df, benign_sample]))

balanced_df = pd.concat(balanced_parts)
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(balanced_df[" attack_type"].value_counts())

 attack_type
Benign         13832
FTP-Patator     7935
SSH-Patator     5897
Name: count, dtype: int64

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/BruteForce_clean.csv",
    index=False
)

# **8.Wednesday-workingHours.pcap_ISCX**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CICIDS2017/Wednesday-workingHours.pcap_ISCX.csv")

df[' Label'].value_counts()

 Label
BENIGN              440031
DoS Hulk            231073
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Heartbleed              11
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df[" label"] = df[" Label"].str.strip()
def map_attack(row):
    if row == "BENIGN":
        return "Benign", "Benign"
    elif "DoS" in row:
        return "DoS", row.replace("DoS ", "")
    elif row == "Heartbleed":
        return "Exploit", "Heartbleed"
    else:
        return "Other", row

df[[" attack_family", " attack_type"]] = df[" label"].apply(
    lambda x: pd.Series(map_attack(x))
)

df.drop(columns=[" Label"], inplace=True)

In [ ]:
balanced_parts = []

attack_types = ["Hulk", "GoldenEye", "slowloris", "Slowhttptest", "Heartbleed"]

for attack in attack_types:
    attack_df = df[df[" attack_type"] == attack]
    benign_df = df[df[" attack_type"] == "Benign"]

    # Special case: Heartbleed (very rare)
    if attack == "Heartbleed":
        benign_sample = benign_df.sample(
            n=len(attack_df),
            random_state=42
        )
        balanced_parts.append(pd.concat([attack_df, benign_sample]))
    else:
        benign_sample = benign_df.sample(
            n=len(attack_df),
            random_state=42
        )
        balanced_parts.append(pd.concat([attack_df, benign_sample]))

balanced_df = pd.concat(balanced_parts)
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(balanced_df[" attack_type"].value_counts())

 attack_type
Benign          251723
Hulk            230124
GoldenEye        10293
slowloris         5796
Slowhttptest      5499
Heartbleed          11
Name: count, dtype: int64

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/DoS_clean.csv",
    index=False
)

# **Merge the 8 CICIDS2017 files**

In [ ]:
files = [
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/Benign_only.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/Bot_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/BruteForce_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/DDoS_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/DoS_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/Infiltration_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/PortScan_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017/WebAttack_clean.csv"
]

# Strip leading/trailing spaces from all column names
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'label', 'attack_family', 'attack_type']

In [ ]:
dfs = []

for f in files:
    df = pd.read_csv(f)
    df.columns = df.columns.str.strip()   # 🔥 fix spaces
    dfs.append(df)

cicids2017_full = pd.concat(dfs, ignore_index=True)

In [ ]:
print(cicids2017_full.columns.tolist())

['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'label', 'attack_family', 'attack_type']

In [ ]:
print(cicids2017_full["attack_type"].value_counts())
print("\n")
print(cicids2017_full["attack_family"].value_counts())

attack_type
Benign           1024186
Hulk              230124
PortScan          127292
DDoS               97686
GoldenEye          10293
FTP-Patator         7935
SSH-Patator         5897
slowloris           5796
Slowhttptest        5499
Bot                 1956
Brute Force         1507
XSS                  652
Infiltration          36
SQL Injection         21
Heartbleed            11
Name: count, dtype: int64


attack_family
Benign            1024186
DoS                251712
Reconnaissance     127292
DDoS                97686
BruteForce          13832
WebAttack            2180
Botnet               1956
Infiltration           36
Exploit                11
Name: count, dtype: int64

In [ ]:
cicids2017_full.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017_full_clean.csv",
    index=False
)

In [1]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017_full_clean.csv")
df['label'].value_counts()

NameError: name 'pd' is not defined

# Standardize BruteForce naming

In [ ]:
df["label"] = df["label"].replace({
    "SSH-Patator": "SSH-BruteForce",
    "FTP-Patator": "FTP-BruteForce"
})

df["attack_type"] = df["attack_type"].replace({
    "SSH-Patator": "SSH-BruteForce",
    "FTP-Patator": "FTP-BruteForce"
})

# attack_family already correct, but enforce it
df.loc[df["attack_type"].str.contains("BruteForce", na=False), "attack_family"] = "BruteForce"

print(df["attack_type"].value_counts())

attack_type
Benign            1024186
Hulk               230124
PortScan           127292
DDoS                97686
GoldenEye           10293
FTP-BruteForce       7935
SSH-BruteForce       5897
slowloris            5796
Slowhttptest         5499
Bot                  1956
Brute Force          1507
XSS                   652
Infiltration           36
SQL Injection          21
Heartbleed             11
Name: count, dtype: int64

In [ ]:
print(df["label"].value_counts())

label
BENIGN                        1024186
DoS Hulk                       230124
PortScan                       127292
DDoS                            97686
DoS GoldenEye                   10293
FTP-BruteForce                   7935
SSH-BruteForce                   5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1956
Web Attack - Brute Force         1507
Web Attack - XSS                  652
Infiltration                       36
Web Attack - SQL Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017_full_clean.csv",
    index=False
)

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CICIDS2017_full_clean.csv")
df['label'].value_counts()

label
BENIGN                        1024186
DoS Hulk                       230124
PortScan                       127292
DDoS                            97686
DoS GoldenEye                   10293
FTP-BruteForce                   7935
SSH-BruteForce                   5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1956
Web Attack - Brute Force         1507
Web Attack - XSS                  652
Infiltration                       36
Web Attack - SQL Injection         21
Heartbleed                         11
Name: count, dtype: int64