# **1. Botnet**

In [49]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/Botnet.csv")

df['Label'].value_counts()

Label
Benign    627052
Bot       144535
Name: count, dtype: int64

# Clean NaN / Inf

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

# Normalize label text

In [ ]:
df['Label'] = df['Label'].str.strip()

# Create consistent labels

In [ ]:
df['attack_family'] = df['Label'].apply(
    lambda x: 'Benign' if x == 'Benign' else 'Botnet'
)

df['attack_type'] = df['Label'].apply(
    lambda x: 'Benign' if x == 'Benign' else 'Bot'
)

# Balance classes

In [ ]:
attack_df = df[df['attack_type'] == 'Bot']
benign_df = df[df['attack_type'] == 'Benign']

benign_sample = benign_df.sample(
    n=len(attack_df),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42)

# Save clean dataset

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Botnet_clean.csv",
    index=False
)

# **2.Bruteforce**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/Bruteforce.csv")

df['Label'].value_counts()

Label
Benign            525245
SSH-Bruteforce     94048
FTP-BruteForce        53
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df['Label'] = df['Label'].str.strip()

In [ ]:
df['attack_family'] = df['Label'].apply(
    lambda x: 'Benign' if x == 'Benign' else 'BruteForce'
)

In [ ]:
def map_attack_type(x):
    if x == 'Benign':
        return 'Benign'
    elif 'SSH' in x:
        return 'SSH-Bruteforce'
    elif 'FTP' in x:
        return 'FTP-Bruteforce'
    else:
        return 'BruteForce-Other'

df['attack_type'] = df['Label'].apply(map_attack_type)

In [ ]:
attack_df = df[df['attack_family'] == 'BruteForce']
benign_df = df[df['attack_family'] == 'Benign']

benign_sample = benign_df.sample(
    n=len(attack_df),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42)

In [ ]:
print(balanced_df['attack_family'].value_counts())
print(balanced_df['attack_type'].value_counts())

attack_family
BruteForce    94101
Benign        94101
Name: count, dtype: int64
attack_type
Benign            94101
SSH-Bruteforce    94048
FTP-Bruteforce       53
Name: count, dtype: int64

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Bruteforce_clean.csv",
    index=False
)

# 3.DDoS1

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/DDoS1.csv")

df['Label'].value_counts()

Label
DDoS attacks-LOIC-HTTP    575364
Benign                    379482
Name: count, dtype: int64

In [ ]:

df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df['Label'] = df['Label'].str.strip()

In [ ]:
df['attack_family'] = df['Label'].apply(
    lambda x: 'Benign' if x == 'Benign' else 'DDoS'
)

df['attack_type'] = df['Label'].apply(
    lambda x: 'Benign' if x == 'Benign' else 'DDoS_LOIC_HTTP'
)

In [ ]:
attack_df = df[df['attack_type'] == 'DDoS_LOIC_HTTP']
benign_df = df[df['attack_type'] == 'Benign']

attack_sample = attack_df.sample(n=len(benign_df), random_state=42)

balanced_df = pd.concat([attack_sample, benign_df])
balanced_df = balanced_df.sample(frac=1, random_state=42)

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/DDoS1_clean.csv",
    index=False
)

# 4. DDoS2

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/DDoS2.csv")

df['Label'].value_counts()

Label
Benign                  360805
DDOS attack-HOIC        198861
DDOS attack-LOIC-UDP      1730
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df['Label'] = df['Label'].str.strip()

def map_attack(row):
    if row == 'Benign':
        return ('Benign', 'Benign')
    elif 'HOIC' in row:
        return ('DDoS', 'DDoS-HOIC')
    elif 'LOIC' in row:
        return ('DDoS', 'DDoS-LOIC-UDP')
    else:
        return ('Other', 'Other')

df[['attack_family', 'attack_type']] = df['Label'].apply(
    lambda x: pd.Series(map_attack(x))
)

In [ ]:
attack_df = df[df['attack_family'] == 'DDoS']
benign_df = df[df['attack_family'] == 'Benign']

benign_sample = benign_df.sample(
    n=len(attack_df),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample]).sample(frac=1, random_state=42)

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/DDoS2_clean.csv",
    index=False
)

# 5.DoS1

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/DoS1.csv")

df['Label'].value_counts()

Label
Benign                   743498
DoS attacks-GoldenEye     41406
DoS attacks-Slowloris      9908
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df['Label'] = df['Label'].str.strip()

df['attack_family'] = df['Label'].apply(
    lambda x: 'Benign' if x == 'Benign' else 'DoS'
)

def map_attack_type(label):
    if label == 'Benign':
        return 'Benign'
    elif 'GoldenEye' in label:
        return 'GoldenEye'
    elif 'Slowloris' in label:
        return 'Slowloris'
    else:
        return 'DoS'

df['attack_type'] = df['Label'].apply(map_attack_type)

In [ ]:
attack_df = df[df['attack_family'] == 'DoS']
benign_df = df[df['attack_family'] == 'Benign']

# 1:2 ratio (safe for large datasets)
benign_sample = benign_df.sample(
    n=min(len(attack_df) * 2, len(benign_df)),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42)

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/DoS1_clean.csv",
    index=False
)

# 6.DoS2

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/DoS2.csv")

df['Label'].value_counts()

Label
Benign                      446619
DoS attacks-Hulk            145199
DoS attacks-SlowHTTPTest        55
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df['Label'] = df['Label'].str.strip()
def map_attack(label):
    if label == "Benign":
        return ("Benign", "Benign")
    elif "Hulk" in label:
        return ("DoS", "Hulk")
    elif "SlowHTTPTest" in label:
        return ("DoS", "SlowHTTPTest")
    else:
        return ("DoS", "Other_DoS")

df[['attack_family', 'attack_type']] = df['Label'].apply(
    lambda x: pd.Series(map_attack(x))
)

In [ ]:
attack_df = df[df['attack_family'] == "DoS"]
benign_df = df[df['attack_family'] == "Benign"]

# Limit benign to max 2x attacks
max_benign = min(len(benign_df), len(attack_df) * 2)

benign_sample = benign_df.sample(
    n=max_benign,
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42)

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/DoS2_clean.csv",
    index=False
)

# 7.Infil1

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/Infil1.csv")

df['Label'].value_counts()

Label
Benign           400424
Infilteration     56449
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df["Label"] = df["Label"].str.strip()

df["attack_family"] = df["Label"].apply(
    lambda x: "Benign" if x == "Benign" else "Infiltration"
)

df["attack_type"] = df["Label"].apply(
    lambda x: "Benign" if x == "Benign" else "Infiltration"
)

In [ ]:
attack_df = df[df["attack_family"] == "Infiltration"]
benign_df = df[df["attack_family"] == "Benign"]

benign_sample = benign_df.sample(
    n=min(len(benign_df), len(attack_df) * 2),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42)

In [ ]:
balanced_df["attack_family"].value_counts()

attack_family
Benign          112898
Infiltration     56449
Name: count, dtype: int64

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Infil1_clean.csv",
    index=False
)

# 8.Infil2

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/Infil2.csv")

df['Label'].value_counts()

Label
Benign           187136
Infilteration     62034
Name: count, dtype: int64

In [ ]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
df['Label'] = df['Label'].str.strip()

df['attack_family'] = df['Label'].apply(
    lambda x: 'Benign' if x == 'Benign' else 'Infiltration'
)

df['attack_type'] = df['Label'].apply(
    lambda x: 'Benign' if x == 'Benign' else 'Infiltration'
)

In [ ]:
attack_df = df[df['attack_family'] == 'Infiltration']
benign_df = df[df['attack_family'] == 'Benign']

benign_sample = benign_df.sample(
    n=min(len(benign_df), len(attack_df) * 2),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample])
balanced_df = balanced_df.sample(frac=1, random_state=42)

In [ ]:
balanced_df['attack_family'].value_counts()

attack_family
Benign          124068
Infiltration     62034
Name: count, dtype: int64

In [ ]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Infil2_clean.csv",
    index=False
)

# 9.Web1

In [58]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/Web1.csv")

df['Label'].value_counts()

Label
Benign              829883
Brute Force -Web       228
Brute Force -XSS        79
SQL Injection           34
Name: count, dtype: int64

In [59]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [61]:
df["Label"] = df["Label"].astype(str).str.strip().str.lower()

In [62]:
def map_web_attack(label):
    if label == "benign":
        return "Benign", "Benign"
    elif "brute force" in label and "web" in label:
        return "WebAttack", "Web_BruteForce"
    elif "xss" in label:
        return "WebAttack", "XSS"
    elif "sql" in label:
        return "WebAttack", "SQL_Injection"
    else:
        return "Other", "Other"

In [63]:
df[["attack_family", "attack_type"]] = df["Label"].apply(
    lambda x: pd.Series(map_web_attack(x))
)

In [67]:
df["attack_type"].value_counts()

attack_type
Benign            829883
Web_BruteForce       228
XSS                   79
SQL_Injection         34
Name: count, dtype: int64

In [69]:
benign_df = df[df["attack_family"] == "Benign"]

benign_sample = benign_df.sample(
    n=min(len(benign_df), len(attack_df) * 3),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample]).sample(frac=1, random_state=42)

In [70]:
balanced_df['attack_type'].value_counts()

attack_type
Benign            1023
Web_BruteForce     228
XSS                 79
SQL_Injection       34
Name: count, dtype: int64

In [71]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Web1_clean.csv",
    index=False
)

# 10.Web2

In [79]:
df = pd.read_csv("/content/drive/MyDrive/NIDS_Tharusha/datasets_raw/CSE-CICIDS2018/Web2.csv")

df['Label'].value_counts()

Label
Benign              828864
Brute Force -Web       340
Brute Force -XSS       150
SQL Injection           51
Name: count, dtype: int64

In [80]:
df["Label"] = df["Label"].astype(str).str.strip().str.lower()
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

In [82]:
def map_web_attack(label):
    if label == "benign":
        return "Benign", "Benign"
    elif "brute force" in label and "web" in label:
        return "WebAttack", "Web_BruteForce"
    elif "xss" in label:
        return "WebAttack", "XSS"
    elif "sql" in label:
        return "WebAttack", "SQL_Injection"
    else:
        return "Other", "Other"

In [83]:
df[["attack_family", "attack_type"]] = df["Label"].apply(
    lambda x: pd.Series(map_web_attack(x))
)

In [84]:
df["attack_type"].value_counts()

attack_type
Benign            828864
Web_BruteForce       340
XSS                  150
SQL_Injection         51
Name: count, dtype: int64

In [86]:
attack_df = df[df["attack_family"] == "WebAttack"]
benign_df = df[df["attack_family"] == "Benign"]

benign_sample = benign_df.sample(
    n=min(len(benign_df), len(attack_df) * 3),
    random_state=42
)

balanced_df = pd.concat([attack_df, benign_sample]).sample(frac=1, random_state=42)

In [87]:
balanced_df["attack_family"].value_counts()
balanced_df["attack_type"].value_counts()

attack_type
Benign            1623
Web_BruteForce     340
XSS                150
SQL_Injection       51
Name: count, dtype: int64

In [88]:
balanced_df.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Web2_clean.csv",
    index=False
)

# ***CSECICIDS2018 clean dataset***

In [89]:
files = [
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Botnet_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Bruteforce_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/DDoS1_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/DDoS2_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/DoS1_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/DoS2_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Infil1_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Infil2_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Web1_clean.csv",
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSE-CICIDS2018/Web2_clean.csv"
]

dfs = [pd.read_csv(f) for f in files]

In [91]:
base_cols = dfs[0].columns

for i, df in enumerate(dfs):
    if not base_cols.equals(df.columns):
        print(f"❌ Column mismatch in file {i}")

In [92]:
csecicids2018_full = pd.concat(dfs, ignore_index=True)

print("Final shape:", csecicids2018_full.shape)

Final shape: (2586099, 80)

In [93]:
print(csecicids2018_full["attack_family"].value_counts())
print("\n")
print(csecicids2018_full["attack_type"].value_counts())

attack_family
Benign          1451457
DDoS             580073
DoS              196568
Botnet           144535
Infiltration     118483
BruteForce        94101
WebAttack           882
Name: count, dtype: int64


attack_type
Benign            1451457
DDoS_LOIC_HTTP     379482
DDoS-HOIC          198861
Hulk               145199
Bot                144535
Infiltration       118483
SSH-Bruteforce      94048
GoldenEye           41406
Slowloris            9908
DDoS-LOIC-UDP        1730
Web_BruteForce        568
XSS                   229
SQL_Injection          85
SlowHTTPTest           55
FTP-Bruteforce         53
Name: count, dtype: int64

In [94]:
csecicids2018_full.columns = csecicids2018_full.columns.str.strip()

In [95]:
if "Label" in csecicids2018_full.columns:
    csecicids2018_full.drop(columns=["Label"], inplace=True)

In [96]:
csecicids2018_full.to_csv(
    "/content/drive/MyDrive/NIDS_Tharusha/datasets_clean/CSECICIDS2018_full_clean.csv",
    index=False
)